# Generated by Django 5.1.7 on 2025-04-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_category_gamestone_alter_user_phone_number_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamestone',
            new_name='Gemestone',
        ),
        migrations.CreateModel(
            name='ProductGemestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='members.gemestone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemestones', to='members.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductGamestone',
        ),
    ]
