# Generated by Django 5.1.7 on 2025-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_gamestone_gemestone_productgemestone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='imgurl',
        ),
        migrations.RemoveField(
            model_name='reviewimg',
            name='imgurl',
        ),
        migrations.AddField(
            model_name='productimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='reviewimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
