# Generated by Django 5.1.7 on 2025-04-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_productimg_imgurl_remove_reviewimg_imgurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgemestone',
            old_name='gamestone',
            new_name='gemestone',
        ),
    ]
