# Generated by Django 5.1 on 2025-05-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_product_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
