# Generated by Django 5.1 on 2025-06-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgemestone',
            name='gemestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='members.gemestone'),
        ),
    ]
