# Generated by Django 5.1 on 2025-06-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_productgemestone_gemestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
