# Generated by Django 5.1 on 2025-06-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка, %')),
                ('end_time', models.DateTimeField(verbose_name='Конец акции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.category', verbose_name='Категория распродажи')),
            ],
            options={
                'verbose_name': 'Событие распродажи',
                'verbose_name_plural': 'События распродаж',
            },
        ),
    ]
